services:
  findapi-postgres:
    image: postgres:17
    container_name: findapi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - findapi-postgres-data:/var/lib/postgresql/data

volumes:
  findapi-postgres-data:
